# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x0b\x61uthPackage\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x1f\n\x0eVerifyResponse\x12\r\n\x05token\x18\x01 \x01(\t2K\n\x04\x41uth\x12\x43\n\x06Verify\x12\x1a.authPackage.VerifyRequest\x1a\x1b.authPackage.VerifyResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFYREQUEST._serialized_start=37
  _VERIFYREQUEST._serialized_end=67
  _VERIFYRESPONSE._serialized_start=69
  _VERIFYRESPONSE._serialized_end=100
  _AUTH._serialized_start=102
  _AUTH._serialized_end=177
# @@protoc_insertion_point(module_scope)
